/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */

export interface AdminSessionListItem {
	id: string;
	surveyId: string;
	stage: string;
	completionScore: number;
	startedAt: string;
	/** @nullable */
	completedAt: string | null;
}
