/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSessionDetailExtractedCase } from './adminSessionDetailExtractedCase';
import type { Session } from './session';

export interface AdminSessionDetail {
  session: Session;
  /** @nullable */
  extractedCase: AdminSessionDetailExtractedCase;
}
