/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type AdminSessionDetailExtractedCase = { [key: string]: unknown | null } | null;
