/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */
import type { RubricCriteria } from "./rubricCriteria";

export interface DetailRubric {
	id: string;
	surveyId: string;
	slotKey: string;
	status: string;
	criteria: RubricCriteria;
	generatedFrom: string[];
	createdAt: string;
	/** @nullable */
	activatedAt: string | null;
}
