/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */

export interface ExemplarAnswer {
	id: string;
	surveyId: string;
	/** @nullable */
	sessionId: string | null;
	slotKey: string;
	rawText: string;
	extractedValue?: unknown | null;
	/** @nullable */
	pickedBy: string | null;
	/** @nullable */
	notes: string | null;
	createdAt: string;
}
