/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */
import type { RubricDimensionLevels } from "./rubricDimensionLevels";

export interface RubricDimension {
	name: string;
	description: string;
	weight: number;
	levels: RubricDimensionLevels;
}
