/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */
import type { RubricDimension } from "./rubricDimension";

export interface RubricCriteria {
	slot_key: string;
	version: number;
	dimensions: RubricDimension[];
}
