/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */

export interface SendMessageResponse {
  message: string;
  stage: string;
  completionScore: number;
  shouldEnd: boolean;
  safetyWarning?: string;
}
