/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */

export interface SlotCard {
	slotKey: string;
	label: string;
	extractedValue?: unknown | null;
	isFilled: boolean;
	isDetailScorable: boolean;
	/** @nullable */
	detailScore: number | null;
	isPickedUp: boolean;
}
