/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AI Interview API
 * OpenAPI spec version: 1.0.0
 */

export interface Survey {
	id: string;
	title: string;
	description: string;
	theme: string;
	estimatedMinutes: number;
	isActive: boolean;
	createdAt: string;
}
